(deftheme base16-pasque
  "Created 2021-12-15.")

(custom-theme-set-variables
 'base16-pasque
 '(ansi-color-names-vector ["#271c3a" "#a92258" "#c6914b" "#804ead" "#8e7dc6" "#953b9d" "#8e7dc6" "#dedcdf"]))

(custom-theme-set-faces
 'base16-pasque
 '(border ((((type graphic)) (:background "#5d5766")) (((min-colors 256)) (:background "brightblack")) (t (:background "brightblack"))))
 '(cursor ((((type graphic)) (:background "#a92258")) (((min-colors 256)) (:background "red")) (t (:background "red"))))
 '(fringe ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(header-line ((((type graphic)) (:foreground "#953b9d" :background nil :inherit mode-line)) (((min-colors 256)) (:foreground "magenta" :background nil :inherit mode-line)) (t (:foreground "magenta" :background nil :inherit mode-line))))
 '(highlight ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(link ((((type graphic)) (:foreground "#8e7dc6" :underline t)) (((min-colors 256)) (:foreground "blue" :underline t)) (t (:foreground "blue" :underline t))))
 '(link-visited ((((type graphic)) (:foreground "#953b9d" :underline t)) (((min-colors 256)) (:foreground "magenta" :underline t)) (t (:foreground "magenta" :underline t))))
 '(minibuffer-prompt ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(region ((((type graphic)) (:background "#3e2d5c" :distant-foreground "#dedcdf")) (((min-colors 256)) (:background "brightyellow" :distant-foreground "white")) (t (:background "brightyellow" :distant-foreground "white"))))
 '(secondary-selection ((((type graphic)) (:background "#5d5766" :distant-foreground "#dedcdf")) (((min-colors 256)) (:background "brightblack" :distant-foreground "white")) (t (:background "brightblack" :distant-foreground "white"))))
 '(trailing-whitespace ((((type graphic)) (:foreground "#804ead" :background "#7263aa")) (((min-colors 256)) (:foreground "yellow" :background "cyan")) (t (:foreground "yellow" :background "cyan"))))
 '(vertical-border ((((type graphic)) (:foreground "#3e2d5c")) (((min-colors 256)) (:foreground "brightyellow")) (t (:foreground "brightyellow"))))
 '(widget-button ((((type graphic)) (:underline t)) (((min-colors 256)) (:underline t)) (t (:underline t))))
 '(widget-field ((((type graphic)) (:background "#5d5766" :box (:line-width 1 :color "#edeaef"))) (((min-colors 256)) (:background "brightblack" :box (:line-width 1 :color "brightmagenta"))) (t (:background "brightblack" :box (:line-width 1 :color "brightmagenta")))))
 '(error ((((type graphic)) (:foreground "#a92258" :weight bold)) (((min-colors 256)) (:foreground "red" :weight bold)) (t (:foreground "red" :weight bold))))
 '(warning ((((type graphic)) (:foreground "#918889" :weight bold)) (((min-colors 256)) (:foreground "brightred" :weight bold)) (t (:foreground "brightred" :weight bold))))
 '(success ((((type graphic)) (:foreground "#c6914b" :weight bold)) (((min-colors 256)) (:foreground "green" :weight bold)) (t (:foreground "green" :weight bold))))
 '(shadow ((((type graphic)) (:foreground "#5d5766")) (((min-colors 256)) (:foreground "brightblack")) (t (:foreground "brightblack"))))
 '(compilation-column-number ((((type graphic)) (:foreground "#804ead")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(compilation-line-number ((((type graphic)) (:foreground "#804ead")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(compilation-mode-line-exit ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(compilation-mode-line-fail ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(compilation-mode-line-run ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(custom-variable-tag ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(custom-group-tag ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(custom-state ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(font-lock-builtin-face ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(font-lock-comment-delimiter-face ((((type graphic)) (:foreground "#3e2d5c")) (((min-colors 256)) (:foreground "brightyellow")) (t (:foreground "brightyellow"))))
 '(font-lock-comment-face ((((type graphic)) (:foreground "#5d5766")) (((min-colors 256)) (:foreground "brightblack")) (t (:foreground "brightblack"))))
 '(font-lock-constant-face ((((type graphic)) (:foreground "#918889")) (((min-colors 256)) (:foreground "brightred")) (t (:foreground "brightred"))))
 '(font-lock-doc-face ((((type graphic)) (:foreground "#bebcbf")) (((min-colors 256)) (:foreground "brightblue")) (t (:foreground "brightblue"))))
 '(font-lock-function-name-face ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(font-lock-keyword-face ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(font-lock-negation-char-face ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(font-lock-preprocessor-face ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(font-lock-regexp-grouping-backslash ((((type graphic)) (:foreground "#804ead")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(font-lock-regexp-grouping-construct ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(font-lock-string-face ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(font-lock-type-face ((((type graphic)) (:foreground "#804ead")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(font-lock-variable-name-face ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(font-lock-warning-face ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(match ((((type graphic)) (:foreground "#8e7dc6" :background "#100323" :inverse-video t)) (((min-colors 256)) (:foreground "blue" :background "brightgreen" :inverse-video t)) (t (:foreground "blue" :background "brightgreen" :inverse-video t))))
 '(isearch ((((type graphic)) (:foreground "#804ead" :background "#100323" :inverse-video t)) (((min-colors 256)) (:foreground "yellow" :background "brightgreen" :inverse-video t)) (t (:foreground "yellow" :background "brightgreen" :inverse-video t))))
 '(lazy-highlight ((((type graphic)) (:foreground "#7263aa" :background "#100323" :inverse-video t)) (((min-colors 256)) (:foreground "cyan" :background "brightgreen" :inverse-video t)) (t (:foreground "cyan" :background "brightgreen" :inverse-video t))))
 '(isearch-fail ((((type graphic)) (:background "#100323" :inverse-video t :inherit font-lock-warning-face)) (((min-colors 256)) (:background "brightgreen" :inverse-video t :inherit font-lock-warning-face)) (t (:background "brightgreen" :inverse-video t :inherit font-lock-warning-face))))
 '(line-number ((((type graphic)) (:foreground "#5d5766" :background "#100323")) (((min-colors 256)) (:foreground "brightblack" :background "brightgreen")) (t (:foreground "brightblack" :background "brightgreen"))))
 '(line-number-current-line ((((type graphic)) (:inherit fringe)) (((min-colors 256)) (:inherit fringe)) (t (:inherit fringe))))
 '(mode-line ((((type graphic)) (:foreground "#bebcbf" :background "#3e2d5c" :box nil)) (((min-colors 256)) (:foreground "brightblue" :background "brightyellow" :box nil)) (t (:foreground "brightblue" :background "brightyellow" :box nil))))
 '(mode-line-buffer-id ((((type graphic)) (:foreground "#c6914b" :background nil)) (((min-colors 256)) (:foreground "green" :background nil)) (t (:foreground "green" :background nil))))
 '(mode-line-emphasis ((((type graphic)) (:foreground "#edeaef" :slant italic)) (((min-colors 256)) (:foreground "brightmagenta" :slant italic)) (t (:foreground "brightmagenta" :slant italic))))
 '(mode-line-highlight ((((type graphic)) (:foreground "#953b9d" :box nil :weight bold)) (((min-colors 256)) (:foreground "magenta" :box nil :weight bold)) (t (:foreground "magenta" :box nil :weight bold))))
 '(mode-line-inactive ((((type graphic)) (:foreground "#5d5766" :background "#100323" :box nil)) (((min-colors 256)) (:foreground "brightblack" :background "brightgreen" :box nil)) (t (:foreground "brightblack" :background "brightgreen" :box nil))))
 '(diff-added ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(diff-changed ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(diff-removed ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(diff-header ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(diff-file-header ((((type graphic)) (:background "#3e2d5c")) (((min-colors 256)) (:background "brightyellow")) (t (:background "brightyellow"))))
 '(diff-hunk-header ((((type graphic)) (:foreground "#953b9d" :background "#100323")) (((min-colors 256)) (:foreground "magenta" :background "brightgreen")) (t (:foreground "magenta" :background "brightgreen"))))
 '(eldoc-highlight-function-argument ((((type graphic)) (:foreground "#c6914b" :weight bold)) (((min-colors 256)) (:foreground "green" :weight bold)) (t (:foreground "green" :weight bold))))
 '(gnus-summary-normal-unread ((((type graphic)) (:foreground "#8e7dc6" :weight normal)) (((min-colors 256)) (:foreground "blue" :weight normal)) (t (:foreground "blue" :weight normal))))
 '(gnus-summary-normal-read ((((type graphic)) (:foreground "#edeaef" :weight normal)) (((min-colors 256)) (:foreground "brightmagenta" :weight normal)) (t (:foreground "brightmagenta" :weight normal))))
 '(gnus-summary-normal-ancient ((((type graphic)) (:foreground "#7263aa" :weight normal)) (((min-colors 256)) (:foreground "cyan" :weight normal)) (t (:foreground "cyan" :weight normal))))
 '(gnus-summary-normal-ticked ((((type graphic)) (:foreground "#918889" :weight normal)) (((min-colors 256)) (:foreground "brightred" :weight normal)) (t (:foreground "brightred" :weight normal))))
 '(gnus-summary-low-unread ((((type graphic)) (:foreground "#bebcbf" :weight normal)) (((min-colors 256)) (:foreground "brightblue" :weight normal)) (t (:foreground "brightblue" :weight normal))))
 '(gnus-summary-low-read ((((type graphic)) (:foreground "#bebcbf" :weight normal)) (((min-colors 256)) (:foreground "brightblue" :weight normal)) (t (:foreground "brightblue" :weight normal))))
 '(gnus-summary-low-ancient ((((type graphic)) (:foreground "#bebcbf" :weight normal)) (((min-colors 256)) (:foreground "brightblue" :weight normal)) (t (:foreground "brightblue" :weight normal))))
 '(gnus-summary-high-unread ((((type graphic)) (:foreground "#804ead" :weight normal)) (((min-colors 256)) (:foreground "yellow" :weight normal)) (t (:foreground "yellow" :weight normal))))
 '(gnus-summary-high-read ((((type graphic)) (:foreground "#c6914b" :weight normal)) (((min-colors 256)) (:foreground "green" :weight normal)) (t (:foreground "green" :weight normal))))
 '(gnus-summary-high-ancient ((((type graphic)) (:foreground "#c6914b" :weight normal)) (((min-colors 256)) (:foreground "green" :weight normal)) (t (:foreground "green" :weight normal))))
 '(gnus-summary-high-ticked ((((type graphic)) (:foreground "#918889" :weight normal)) (((min-colors 256)) (:foreground "brightred" :weight normal)) (t (:foreground "brightred" :weight normal))))
 '(gnus-summary-cancelled ((((type graphic)) (:foreground "#a92258" :background nil :weight normal)) (((min-colors 256)) (:foreground "red" :background nil :weight normal)) (t (:foreground "red" :background nil :weight normal))))
 '(gnus-group-mail-low ((((type graphic)) (:foreground "#bebcbf")) (((min-colors 256)) (:foreground "brightblue")) (t (:foreground "brightblue"))))
 '(gnus-group-mail-low-empty ((((type graphic)) (:foreground "#bebcbf")) (((min-colors 256)) (:foreground "brightblue")) (t (:foreground "brightblue"))))
 '(gnus-group-mail-1 ((((type graphic)) (:foreground nil :weight normal :inherit outline-1)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-1)) (t (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-mail-2 ((((type graphic)) (:foreground nil :weight normal :inherit outline-2)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-2)) (t (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-mail-3 ((((type graphic)) (:foreground nil :weight normal :inherit outline-3)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-3)) (t (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-mail-1-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-mail-1)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-mail-1)) (t (:foreground "brightblue" :inherit gnus-group-mail-1))))
 '(gnus-group-mail-2-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-mail-2)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-mail-2)) (t (:foreground "brightblue" :inherit gnus-group-mail-2))))
 '(gnus-group-mail-3-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-mail-3)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-mail-3)) (t (:foreground "brightblue" :inherit gnus-group-mail-3))))
 '(gnus-group-news-1 ((((type graphic)) (:foreground nil :weight normal :inherit outline-5)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-5)) (t (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-news-2 ((((type graphic)) (:foreground nil :weight normal :inherit outline-6)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-6)) (t (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-news-3 ((((type graphic)) (:foreground nil :weight normal :inherit outline-7)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-7)) (t (:foreground nil :weight normal :inherit outline-7))))
 '(gnus-group-news-4 ((((type graphic)) (:foreground nil :weight normal :inherit outline-8)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-8)) (t (:foreground nil :weight normal :inherit outline-8))))
 '(gnus-group-news-5 ((((type graphic)) (:foreground nil :weight normal :inherit outline-1)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-1)) (t (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-news-6 ((((type graphic)) (:foreground nil :weight normal :inherit outline-2)) (((min-colors 256)) (:foreground nil :weight normal :inherit outline-2)) (t (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-news-1-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-news-1)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-news-1)) (t (:foreground "brightblue" :inherit gnus-group-news-1))))
 '(gnus-group-news-2-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-news-2)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-news-2)) (t (:foreground "brightblue" :inherit gnus-group-news-2))))
 '(gnus-group-news-3-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-news-3)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-news-3)) (t (:foreground "brightblue" :inherit gnus-group-news-3))))
 '(gnus-group-news-4-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-news-4)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-news-4)) (t (:foreground "brightblue" :inherit gnus-group-news-4))))
 '(gnus-group-news-5-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-news-5)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-news-5)) (t (:foreground "brightblue" :inherit gnus-group-news-5))))
 '(gnus-group-news-6-empty ((((type graphic)) (:foreground "#bebcbf" :inherit gnus-group-news-6)) (((min-colors 256)) (:foreground "brightblue" :inherit gnus-group-news-6)) (t (:foreground "brightblue" :inherit gnus-group-news-6))))
 '(ivy-current-match ((((type graphic)) (:foreground "#918889" :background "#100323")) (((min-colors 256)) (:foreground "brightred" :background "brightgreen")) (t (:foreground "brightred" :background "brightgreen"))))
 '(ivy-minibuffer-match-face-1 ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(ivy-minibuffer-match-face-2 ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(ivy-minibuffer-match-face-3 ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(ivy-minibuffer-match-face-4 ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(ivy-confirm-face ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(ivy-match-required-face ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(ivy-virtual ((((type graphic)) (:foreground "#bebcbf")) (((min-colors 256)) (:foreground "brightblue")) (t (:foreground "brightblue"))))
 '(ivy-action ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(magit-blame-heading ((((type graphic)) (:background "#100323" :foreground "#dedcdf")) (((min-colors 256)) (:background "brightgreen" :foreground "white")) (t (:background "brightgreen" :foreground "white"))))
 '(magit-branch-current ((((type graphic)) (:foreground "#7263aa" :weight bold :box t)) (((min-colors 256)) (:foreground "cyan" :weight bold :box t)) (t (:foreground "cyan" :weight bold :box t))))
 '(magit-branch-local ((((type graphic)) (:foreground "#7263aa" :weight bold)) (((min-colors 256)) (:foreground "cyan" :weight bold)) (t (:foreground "cyan" :weight bold))))
 '(magit-branch-remote ((((type graphic)) (:foreground "#c6914b" :weight bold)) (((min-colors 256)) (:foreground "green" :weight bold)) (t (:foreground "green" :weight bold))))
 '(magit-cherry-equivalent ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(magit-cherry-unmatched ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(magit-diff-context-highlight ((((type graphic)) (:background "#100323" :foreground "#dedcdf")) (((min-colors 256)) (:background "brightgreen" :foreground "white")) (t (:background "brightgreen" :foreground "white"))))
 '(magit-hash ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(magit-header-line ((((type graphic)) (:background "#3e2d5c" :foreground "#dedcdf" :weight bold)) (((min-colors 256)) (:background "brightyellow" :foreground "white" :weight bold)) (t (:background "brightyellow" :foreground "white" :weight bold))))
 '(magit-diff-hunk-heading ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(magit-diff-hunk-heading-highlight ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(magit-log-author ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(magit-process-ng ((((type graphic)) (:foreground "#a92258" :inherit magit-section-heading)) (((min-colors 256)) (:foreground "red" :inherit magit-section-heading)) (t (:foreground "red" :inherit magit-section-heading))))
 '(magit-process-ok ((((type graphic)) (:foreground "#c6914b" :inherit magit-section-heading)) (((min-colors 256)) (:foreground "green" :inherit magit-section-heading)) (t (:foreground "green" :inherit magit-section-heading))))
 '(magit-reflog-amend ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(magit-reflog-checkout ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(magit-reflog-cherry-pick ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(magit-reflog-commit ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(magit-reflog-merge ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(magit-reflog-other ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(magit-reflog-rebase ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(magit-reflog-remote ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(magit-reflog-reset ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(magit-section-highlight ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(magit-signature-bad ((((type graphic)) (:foreground "#a92258" :weight bold)) (((min-colors 256)) (:foreground "red" :weight bold)) (t (:foreground "red" :weight bold))))
 '(magit-signature-error ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(magit-signature-expired ((((type graphic)) (:foreground "#918889")) (((min-colors 256)) (:foreground "brightred")) (t (:foreground "brightred"))))
 '(magit-signature-good ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(magit-signature-revoked ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(magit-signature-untrusted ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(magit-tag ((((type graphic)) (:foreground "#dedcdf")) (((min-colors 256)) (:foreground "white")) (t (:foreground "white"))))
 '(message-header-other ((((type graphic)) (:foreground nil :background nil :weight normal)) (((min-colors 256)) (:foreground nil :background nil :weight normal)) (t (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((type graphic)) (:foreground "#804ead" :weight bold :inherit message-header-other)) (((min-colors 256)) (:foreground "yellow" :weight bold :inherit message-header-other)) (t (:foreground "yellow" :weight bold :inherit message-header-other))))
 '(message-header-to ((((type graphic)) (:foreground "#918889" :weight bold :inherit message-header-other)) (((min-colors 256)) (:foreground "brightred" :weight bold :inherit message-header-other)) (t (:foreground "brightred" :weight bold :inherit message-header-other))))
 '(message-header-cc ((((type graphic)) (:foreground nil :inherit message-header-to)) (((min-colors 256)) (:foreground nil :inherit message-header-to)) (t (:foreground nil :inherit message-header-to))))
 '(message-header-name ((((type graphic)) (:foreground "#8e7dc6" :background nil)) (((min-colors 256)) (:foreground "blue" :background nil)) (t (:foreground "blue" :background nil))))
 '(message-header-newsgroups ((((type graphic)) (:foreground "#7263aa" :background nil :slant normal)) (((min-colors 256)) (:foreground "cyan" :background nil :slant normal)) (t (:foreground "cyan" :background nil :slant normal))))
 '(message-separator ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(org-agenda-structure ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(org-agenda-date ((((type graphic)) (:foreground "#8e7dc6" :underline nil)) (((min-colors 256)) (:foreground "blue" :underline nil)) (t (:foreground "blue" :underline nil))))
 '(org-agenda-done ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(org-agenda-dimmed-todo-face ((((type graphic)) (:foreground "#bebcbf")) (((min-colors 256)) (:foreground "brightblue")) (t (:foreground "brightblue"))))
 '(org-block ((((type graphic)) (:foreground "#dedcdf" :background "#100323")) (((min-colors 256)) (:foreground "white" :background "brightgreen")) (t (:foreground "white" :background "brightgreen"))))
 '(org-block-begin-line ((((type graphic)) (:foreground "#5d5766" :background "#100323")) (((min-colors 256)) (:foreground "brightblack" :background "brightgreen")) (t (:foreground "brightblack" :background "brightgreen"))))
 '(org-code ((((type graphic)) (:foreground "#804ead")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(org-column ((((type graphic)) (:background "#100323")) (((min-colors 256)) (:background "brightgreen")) (t (:background "brightgreen"))))
 '(org-column-title ((((type graphic)) (:weight bold :underline t :inherit org-column)) (((min-colors 256)) (:weight bold :underline t :inherit org-column)) (t (:weight bold :underline t :inherit org-column))))
 '(org-date ((((type graphic)) (:foreground "#953b9d" :underline t)) (((min-colors 256)) (:foreground "magenta" :underline t)) (t (:foreground "magenta" :underline t))))
 '(org-document-info ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(org-document-info-keyword ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(org-document-title ((((type graphic)) (:foreground "#918889" :weight bold :height 1.44)) (((min-colors 256)) (:foreground "brightred" :weight bold :height 1.44)) (t (:foreground "brightred" :weight bold :height 1.44))))
 '(org-done ((((type graphic)) (:foreground "#c6914b" :background "#100323")) (((min-colors 256)) (:foreground "green" :background "brightgreen")) (t (:foreground "green" :background "brightgreen"))))
 '(org-ellipsis ((((type graphic)) (:foreground "#bebcbf")) (((min-colors 256)) (:foreground "brightblue")) (t (:foreground "brightblue"))))
 '(org-footnote ((((type graphic)) (:foreground "#7263aa")) (((min-colors 256)) (:foreground "cyan")) (t (:foreground "cyan"))))
 '(org-formula ((((type graphic)) (:foreground "#a92258")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(org-hide ((((type graphic)) (:foreground "#5d5766")) (((min-colors 256)) (:foreground "brightblack")) (t (:foreground "brightblack"))))
 '(org-link ((((type graphic)) (:foreground "#8e7dc6")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(org-scheduled ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(org-scheduled-previously ((((type graphic)) (:foreground "#918889")) (((min-colors 256)) (:foreground "brightred")) (t (:foreground "brightred"))))
 '(org-scheduled-today ((((type graphic)) (:foreground "#c6914b")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(org-special-keyword ((((type graphic)) (:foreground "#918889")) (((min-colors 256)) (:foreground "brightred")) (t (:foreground "brightred"))))
 '(org-table ((((type graphic)) (:foreground "#953b9d")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(org-todo ((((type graphic)) (:foreground "#a92258" :background "#100323")) (((min-colors 256)) (:foreground "red" :background "brightgreen")) (t (:foreground "red" :background "brightgreen"))))
 '(org-upcoming-deadline ((((type graphic)) (:foreground "#918889")) (((min-colors 256)) (:foreground "brightred")) (t (:foreground "brightred"))))
 '(org-warning ((((type graphic)) (:foreground "#a92258" :weight bold)) (((min-colors 256)) (:foreground "red" :weight bold)) (t (:foreground "red" :weight bold))))
 '(show-paren-match ((((type graphic)) (:foreground "#100323" :background "#8e7dc6")) (((min-colors 256)) (:foreground "brightgreen" :background "blue")) (t (:foreground "brightgreen" :background "blue"))))
 '(show-paren-mismatch ((((type graphic)) (:foreground "#100323" :background "#918889")) (((min-colors 256)) (:foreground "brightgreen" :background "brightred")) (t (:foreground "brightgreen" :background "brightred"))))
 '(term ((((type graphic)) (:foreground "#dedcdf" :background "#271c3a")) (((min-colors 256)) (:foreground "white" :background "black")) (t (:foreground "white" :background "black"))))
 '(term-color-black ((((type graphic)) (:foreground "#3e2d5c" :background "#271c3a")) (((min-colors 256)) (:foreground "brightyellow" :background "black")) (t (:foreground "brightyellow" :background "black"))))
 '(term-color-white ((((type graphic)) (:foreground "#dedcdf" :background "#bbaadd")) (((min-colors 256)) (:foreground "white" :background "brightwhite")) (t (:foreground "white" :background "brightwhite"))))
 '(term-color-red ((((type graphic)) (:foreground "#a92258" :background "#a92258")) (((min-colors 256)) (:foreground "red" :background "red")) (t (:foreground "red" :background "red"))))
 '(term-color-yellow ((((type graphic)) (:foreground "#804ead" :background "#804ead")) (((min-colors 256)) (:foreground "yellow" :background "yellow")) (t (:foreground "yellow" :background "yellow"))))
 '(term-color-green ((((type graphic)) (:foreground "#c6914b" :background "#c6914b")) (((min-colors 256)) (:foreground "green" :background "green")) (t (:foreground "green" :background "green"))))
 '(term-color-cyan ((((type graphic)) (:foreground "#7263aa" :background "#7263aa")) (((min-colors 256)) (:foreground "cyan" :background "cyan")) (t (:foreground "cyan" :background "cyan"))))
 '(term-color-blue ((((type graphic)) (:foreground "#8e7dc6" :background "#8e7dc6")) (((min-colors 256)) (:foreground "blue" :background "blue")) (t (:foreground "blue" :background "blue"))))
 '(term-color-magenta ((((type graphic)) (:foreground "#953b9d" :background "#953b9d")) (((min-colors 256)) (:foreground "magenta" :background "magenta")) (t (:foreground "magenta" :background "magenta"))))
 '(tooltip ((((type graphic)) (:background "#100323" :inherit default)) (((min-colors 256)) (:background "brightgreen" :inherit default)) (t (:background "brightgreen" :inherit default))))
 '(which-func ((((type graphic)) (:foreground "#8e7dc6" :background nil :weight bold)) (((min-colors 256)) (:foreground "blue" :background nil :weight bold)) (t (:foreground "blue" :background nil :weight bold))))
 '(default ((((type graphic)) (:foreground "#dedcdf" :background "#271c3a")) (((min-colors 256)) (:foreground "white" :background "black")) (t (:foreground "white" :background "black")))))

(provide-theme 'base16-pasque)
